// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATnWv_B4Z-fBnKG-TIvArl4nY54knVduQ',
    appId: '1:433274927814:web:07323c2a49164597fc35c7',
    messagingSenderId: '433274927814',
    projectId: 'jk-blog-app',
    authDomain: 'jk-blog-app.firebaseapp.com',
    storageBucket: 'jk-blog-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmtXe-S7001Vy0GyujO8Y0Q0jja8nZHr4',
    appId: '1:433274927814:android:7c0ee4b4d8fa38e1fc35c7',
    messagingSenderId: '433274927814',
    projectId: 'jk-blog-app',
    storageBucket: 'jk-blog-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh1oGOVq7Ld1tCthhikBOK3kCvA4Uc6z8',
    appId: '1:433274927814:ios:0db5c6bffa022659fc35c7',
    messagingSenderId: '433274927814',
    projectId: 'jk-blog-app',
    storageBucket: 'jk-blog-app.appspot.com',
    iosBundleId: 'com.example.jkblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh1oGOVq7Ld1tCthhikBOK3kCvA4Uc6z8',
    appId: '1:433274927814:ios:8857cb31e16646eafc35c7',
    messagingSenderId: '433274927814',
    projectId: 'jk-blog-app',
    storageBucket: 'jk-blog-app.appspot.com',
    iosBundleId: 'com.example.jkblog.RunnerTests',
  );
}
